-- FitTrack PostgreSQL Database Schema
-- Hosted with Supabase
-- Defines the initial database structure for the FitTrack REST API.

-- =========================================================
-- Users
-- =========================================================

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    email TEXT NOT NULL UNIQUE,
    display_name TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'user',
    CONSTRAINT valid_user_role CHECK (role IN ('user', 'admin'))
);

-- =========================================================
-- Exercises
-- =========================================================

CREATE TABLE exercises (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    name TEXT NOT NULL UNIQUE,
    description TEXT,
    category TEXT
);

-- =========================================================
-- Workouts
-- =========================================================

CREATE TABLE workouts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    name TEXT NOT NULL,
    performed_at TIMESTAMPTZ,
    user_id BIGINT NOT NULL,

    CONSTRAINT fk_workout_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);

-- =========================================================
-- Workout Exercises
-- =========================================================

CREATE TABLE workout_exercises (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    workout_id BIGINT NOT NULL,
    exercise_id BIGINT NOT NULL,
    sets BIGINT,
    repetitions BIGINT,
    weight NUMERIC,
    duration_seconds BIGINT,

    CONSTRAINT fk_workout_exercise_workout
        FOREIGN KEY (workout_id)
        REFERENCES workouts(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_workout_exercise_exercise
        FOREIGN KEY (exercise_id)
        REFERENCES exercises(id)
        ON DELETE CASCADE
);
